// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.PWMTalonSRX;
import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMTalonSRX m_driveLeftLeader;
private PWMVictorSPX m_driveLeftFollower;
private MotorControllerGroup m_driveLeft;
private PWMTalonSRX m_driveRightLeader;
private PWMVictorSPX m_driveRightFollower;
private MotorControllerGroup m_driveRight;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public DriveTrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
m_driveLeftLeader = new PWMTalonSRX(1);
 addChild("m_driveLeftLeader",m_driveLeftLeader);
 m_driveLeftLeader.setInverted(false);

m_driveLeftFollower = new PWMVictorSPX(2);
 addChild("m_driveLeftFollower",m_driveLeftFollower);
 m_driveLeftFollower.setInverted(false);

m_driveLeft = new MotorControllerGroup(m_driveLeftLeader, m_driveLeftFollower  );
 addChild("m_driveLeft",m_driveLeft);
 

m_driveRightLeader = new PWMTalonSRX(3);
 addChild("m_driveRightLeader",m_driveRightLeader);
 m_driveRightLeader.setInverted(true);

m_driveRightFollower = new PWMVictorSPX(4);
 addChild("m_driveRightFollower",m_driveRightFollower);
 m_driveRightFollower.setInverted(true);

m_driveRight = new MotorControllerGroup(m_driveRightFollower, m_driveRightLeader  );
 addChild("m_driveRight",m_driveRight);
 


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

