// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class HopperSubsystem extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonSRX m_hopperStage1Leader;
private WPI_VictorSPX m_hopperStage1Follower;
private MotorControllerGroup m_hopperStage1;
private WPI_TalonSRX m_hopperStage2Leader;
private WPI_VictorSPX m_hopperStage2Follower;
private MotorControllerGroup m_hopperStage2;
private DigitalInput m_hopperSensorStage1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public HopperSubsystem() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
m_hopperStage1Leader = new WPI_TalonSRX(6);
 
 

m_hopperStage1Follower = new WPI_VictorSPX(7);
 
 

m_hopperStage1 = new MotorControllerGroup(m_hopperStage1Leader, m_hopperStage1Follower  );
 addChild("m_hopperStage1",m_hopperStage1);
 

m_hopperStage2Leader = new WPI_TalonSRX(8);
 
 

m_hopperStage2Follower = new WPI_VictorSPX(9);
 
 

m_hopperStage2 = new MotorControllerGroup(m_hopperStage2Leader, m_hopperStage2Follower  );
 addChild("m_hopperStage2",m_hopperStage2);
 

m_hopperSensorStage1 = new DigitalInput(12);
 addChild("m_hopperSensorStage1", m_hopperSensorStage1);
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

