package frc.robot.commands;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.CommandBase;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import frc.robot.subsystems.DriveSubsystem;
// import frc.robot.RobotContainer;
import frc.robot.subsystems.VisionSubsystem;

public class cmdTargetOrient extends CommandBase {

    private final DriveSubsystem m_driveSubsystem;

    public cmdTargetOrient(DriveSubsystem subsystem) {

        m_driveSubsystem = subsystem;
        addRequirements(m_driveSubsystem);

    }

    // Called once when this command runs
    @Override
    public void initialize() {
        // RobotContainer.getInstance().m_driveSubsystem.setSteeringAdjustment();
        if(Math.abs(VisionSubsystem.getTx()) > 1.0){
             m_driveSubsystem.setSteeringAdjustment();
        }

     }

    @Override
    public void execute() {
        // RobotContainer.getInstance().m_driveSubsystem.setSteeringAdjustment();
        m_driveSubsystem.setSteeringAdjustment();
     }
    
    @Override
    public boolean isFinished() {
        return false;
    }
    

    public static boolean isTargetOrient(){
        return true; 
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
